# Header
menu:
  Home: /
  Archives: /archives
  分类: /categories/ 
  标签: /tags/ 
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

gitalk:
    enable: true
    github_id: Qign # Github repo owner
    repo: talk  # Repository name to store issues
    client_id: bc302799263ab16814f7 # Github Application Client ID
    client_secret: 1ef5aa28601010f71ce5faa47a9a77c609c445ca   # Github Application Client Secret
    admin_user: Qign # GitHub repo owner and collaborators, only these guys can initialize github issues
    distraction_free_mode: true # Facebook-like distraction free mode
    # Gitalk's display language depends on user's browser or system environment
    # If you want everyone visiting your site to see a uniform language, you can set a force language value
    # Available values: en, es-ES, fr, ru, zh-CN, zh-TW
    language: 


# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
