# config
cover: "http://ptotp34r4.bkt.clouddn.com/cat-1393075_1920%20%281%29.jpg"
logo: /img/logo.png
top_saying:
- title: <font color="white"> Q-Q <span>life</span> Q-Q. </font>
- content: <font color="white"> 每一个不曾起舞的日子都是对生命的辜负。</font>
bottom_saying: 虽然还没想好写点什么，但是总觉得这里放句话比较和谐。
# Content
excerpt_link: Read More

rss: /atom.xml
about: /about

highlightjs: vs

#Works


#duoshuo name
duoshuo:

#disqus name
disqus_shortname:

#fancybox
fancybox: true

# Miscellaneous
github: https://github.com/
twitter: https://twitter.com/
facebook: https://www.facebook.com/
google: https://google.com/
weibo: http://weibo.com/

#about  timeline
timeline: 
- num: 1
  word: 2019/01/01-Start
- num: 2
  word: 2019/11/29-XXX
- num: 3
  word: 2019/02/18-DDD
- num: 4
  word: More

#Links


# Local search
# Dependencies: https://github.com/flashlab/hexo-generator-search
local_search:
  enable: false
  # if auto, trigger search by changing input
  # if manual, trigger search by pressing enter key or search button
  trigger: auto
  # show top n results per article, show all results by setting to -1
  top_n_per_article: 2
